### PR TITLE
Update git-in-here.yml

### PR DESCRIPTION
**Pull request by GettingWeirdKnowledge**
**PR Type:** Updated to add my contribution

**Affiliation:** N/A

**Ticket:** N/A

 
**Checklist:**
- [x] I've read Contributing Guidelines
- [x] I agree to follow the Code of Conduct

### CODE REVIEW

**Comment by GettingWeirdKnowledge** [comment]
YAML validator does not indicate any errors.

**Comment by Lissy93** [comment]
Maybe using a YAML validator will help - there's an error where you've just got an extra space before `question` and `response`

**Comment by GettingWeirdKnowledge** [comment]
> Maybe using a YAML validator will help - there's an error where you've just got an extra space before `question` and `response`
> 
> 

This totally missed my eye and the YAML validator didn't indicate this at first either. Thank you for pointing it out, I have edited it again, should I create a new PR ?

**Comment by Lissy93** [comment]
Thanks!
I've merged it 🎉

**Pull request merged**
