### PR TITLE
Added the resource Git Command Explorer which is a great tool to get …

### PR DESCRIPTION
**Pull request by Rohithv07**
…know about git commands

**PR Type:** resource addition

**Affiliation:** N/A

**Ticket:** N/A

 
**Checklist:**
- [x] I've read Contributing Guidelines
- [x] I agree to follow the Code of Conduct

### CODE REVIEW

**Comment by Rohithv07** [comment]
Through this site, we can just select the options indication what we want to do. Example say I want to "clone", "existing repo to new directory". We just select those options from the drop down and the commands to do it like "git clone <repo-url> <directory>" will be listed with a description below 
"The repo is cloned into the specified directory "directory" with the directory you want"

**Comment by Lissy93** [comment]
Looks awesome 💪
Would you mind just filling out the PR template (just click the    ⃛  in top left, then click Edit)

**Comment by Rohithv07** [comment]
@Lissy93 , could you please add the hacktoberfest label if it is ok

**Comment by Rohithv07** [comment]
Thanks, ⭐️ is also done 👍

**Pull request merged**
